# ä¸€ä¸ª workflowï¼Œåå­—ä¸ºGithub Action Example
name: Build and Deploy

# è§¦å‘ workflow çš„äº‹ä»¶
on: #[ push ]
  push:
    #è§¦å‘åˆ†æ”¯
    branches:
      - main

# ä¸€ä¸ªworkflowç”±æ‰§è¡Œçš„ä¸€é¡¹æˆ–å¤šé¡¹job
jobs:
  # ä¸€ä¸ªjobä»»åŠ¡ï¼Œä»»åŠ¡åä¸ºbuild-and-deploy
  build-and-deploy:
    # runs-on æŒ‡å®šjobä»»åŠ¡è¿è¡Œæ‰€éœ€è¦çš„è™šæ‹Ÿæœºç¯å¢ƒ(å¿…å¡«å­—æ®µ)
    runs-on: ubuntu-latest
    # stepsæ˜¯æ¯ä¸ªJobçš„è¿è¡Œæ­¥éª¤ï¼Œå¯ä»¥åŒ…å«ä¸€ä¸ªæˆ–å¤šä¸ªæ­¥éª¤
    steps:
      # actionå‘½ä»¤ï¼Œåˆ‡æ¢åˆ†æ”¯è·å–æºç 
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
          echo å½“å‰ç¼–è¯‘ç›®å½•ï¼š`pwd`
          ll `pwd`
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.6.2
        run: |
          echo å½“å‰ç›®å½•ï¼š`pwd`
          ll `pwd`
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build-dist # The branch the action should deploy to.
          FOLDER: .vuepress/dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
